$(function(){
    $('.tab_btn').click(function(){
        $(this).addClass('select').siblings().removeClass('select')
    });
});
$(function(){
    $('.snap_tab').hide()
    $('.commercial_tab').hide()
    $('.video_tab').hide();

    $('.btn1').click(function(){
        $('.introduce_tab').show()
        $('.snap_tab').hide()
        $('.commercial_tab').hide()
        $('.video_tab').hide()
    });
    $('.btn2').click(function(){
        $('.snap_tab').show()
        $('.introduce_tab').hide()
        $('.commercial_tab').hide()
        $('.video_tab').hide()
    });
    $('.btn3').click(function(){
        $('.commercial_tab').show()
        $('.introduce_tab').hide()
        $('.snap_tab').hide()
        $('.video_tab').hide()
    });
    $('.btn4').click(function(){
        $('.video_tab').show()
        $('.introduce_tab').hide()
        $('.snap_tab').hide()
        $('.commercial_tab').hide()
        
    });
});